# Generated by Django 3.1.4 on 2021-11-20 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
                ('course_image', models.ImageField(default='default.png', upload_to='course_image')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('status', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=50)),
                ('course', models.ForeignKey(default='Mathematics', on_delete=django.db.models.deletion.CASCADE, to='account.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
