# Generated by Django 3.2.2 on 2021-11-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211123_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
